package com.example.wifinetworkscanner.ui.theme

import androidx.compose.ui.graphics.Color

internal val wifiLightPrimary = Color(0xFF0B57D0)
internal val wifiLightOnPrimary = Color(0xFFFFFFFF)
internal val wifiLightPrimaryContainer = Color(0xFFD8E2FF)
internal val wifiLightOnPrimaryContainer = Color(0xFF001A41)
internal val wifiLightSecondary = Color(0xFF4D5F7C)
internal val wifiLightOnSecondary = Color(0xFFFFFFFF)
internal val wifiLightSecondaryContainer = Color(0xFFD8E3F8)
internal val wifiLightOnSecondaryContainer = Color(0xFF101C32)
internal val wifiLightTertiary = Color(0xFF006B5F)
internal val wifiLightOnTertiary = Color(0xFFFFFFFF)
internal val wifiLightTertiaryContainer = Color(0xFF74F8E3)
internal val wifiLightOnTertiaryContainer = Color(0xFF00201C)
internal val wifiLightError = Color(0xFFBA1A1A)
internal val wifiLightOnError = Color(0xFFFFFFFF)
internal val wifiLightBackground = Color(0xFFFAFDFD)
internal val wifiLightOnBackground = Color(0xFF191C20)
internal val wifiLightSurface = Color(0xFFFAFDFD)
internal val wifiLightOnSurface = Color(0xFF191C20)
internal val wifiLightSurfaceVariant = Color(0xFFE1E2EC)
internal val wifiLightOnSurfaceVariant = Color(0xFF44474F)
internal val wifiLightOutline = Color(0xFF74777F)

internal val wifiDarkPrimary = Color(0xFFA8C7FA)
internal val wifiDarkOnPrimary = Color(0xFF003062)
internal val wifiDarkPrimaryContainer = Color(0xFF0842A0)
internal val wifiDarkOnPrimaryContainer = Color(0xFFD8E2FF)
internal val wifiDarkSecondary = Color(0xFFB8C7E4)
internal val wifiDarkOnSecondary = Color(0xFF22304A)
internal val wifiDarkSecondaryContainer = Color(0xFF354762)
internal val wifiDarkOnSecondaryContainer = Color(0xFFD8E3F8)
internal val wifiDarkTertiary = Color(0xFF53DBC7)
internal val wifiDarkOnTertiary = Color(0xFF003731)
internal val wifiDarkTertiaryContainer = Color(0xFF005047)
internal val wifiDarkOnTertiaryContainer = Color(0xFF74F8E3)
internal val wifiDarkError = Color(0xFFFFB4AB)
internal val wifiDarkOnError = Color(0xFF690005)
internal val wifiDarkBackground = Color(0xFF101418)
internal val wifiDarkOnBackground = Color(0xFFE1E2E8)
internal val wifiDarkSurface = Color(0xFF101418)
internal val wifiDarkOnSurface = Color(0xFFE1E2E8)
internal val wifiDarkSurfaceVariant = Color(0xFF44474F)
internal val wifiDarkOnSurfaceVariant = Color(0xFFC4C6D0)
internal val wifiDarkOutline = Color(0xFF8E9099)